# Copyright (c) 2026 Monolink Systems
# Licensed under AGPLv3 (Nebula Open Source Edition, non-corporate)
"""Mode-aware Core/Panel configuration with secure secret synchronisation."""

from __future__ import annotations

import re
import secrets
from pathlib import Path

from .config import MODE_PROD, DeploymentConfig
from .runner import CommandError, Runner

SECRET_KEYS = (
    "NEBULA_SESSION_SECRET",
    "NEBULA_INSTALLER_TOKEN",
    "NEBULA_PASSWORD_RESET_SECRET",
)


def _parse_env(content: str) -> dict[str, str]:
    values: dict[str, str] = {}
    for raw in content.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]
        values[key.strip()] = value.replace(r"\"", '"').replace(r"\\", "\\")
    return values


def read_env_file(path: Path, runner: Runner | None = None) -> dict[str, str]:
    try:
        return _parse_env(path.read_text(encoding="utf-8"))
    except OSError:
        if runner:
            result = runner.sudo(["cat", str(path)], check=False)
            if result.returncode == 0:
                return _parse_env(result.stdout)
        return {}


def _quote(value: str) -> str:
    if "\n" in value or "\r" in value:
        raise ValueError("Environment values cannot contain newlines")
    return '"' + value.replace("\\", r"\\").replace('"', r"\"") + '"'


def render_env(values: dict[str, str], title: str) -> str:
    lines = [
        f"# {title}",
        "# Generated by Nebula Installer. Unknown keys are preserved on repair.",
        "",
    ]
    lines.extend(f"{key}={_quote(values[key])}" for key in sorted(values))
    return "\n".join(lines) + "\n"


def _write(
    path: Path,
    content: str,
    *,
    config: DeploymentConfig,
    runner: Runner,
    owner: str,
) -> None:
    if config.mode == MODE_PROD:
        runner.install_text(
            path,
            content,
            mode=0o600,
            owner=owner,
            group=owner,
        )
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        path.chmod(0o600)


def _production_secret(existing: str) -> str:
    if len(existing) >= 43 and not existing.startswith(("dev-", "nebula-dev-")):
        return existing
    return secrets.token_urlsafe(48)


def configure_environment(
    config: DeploymentConfig,
    runner: Runner,
    *,
    rotate_secrets: bool = False,
) -> dict[str, str]:
    core_path = config.core_env_path
    legacy_path = config.core_path / ".env"
    core = read_env_file(legacy_path, runner if config.mode == MODE_PROD else None)
    core.update(read_env_file(core_path, runner if config.mode == MODE_PROD else None))

    if config.mode == MODE_PROD:
        origins = f"https://{config.panel_domain}"
        managed = {
            "NEBULA_CORE_HOST": "127.0.0.1",
            "NEBULA_CORE_PORT": str(config.core_port),
            "NEBULA_CORE_WORKERS": "1",
            "NEBULA_CORE_RELOAD": "false",
            "NEBULA_CORE_GRPC_HOST": "127.0.0.1",
            "NEBULA_CORE_GRPC_PORT": "50051",
            "NEBULA_COOKIE_SECURE": "true",
            "NEBULA_SESSION_TTL_SECONDS": "28800",
            "NEBULA_TOTP_VALID_WINDOW": "1",
            "NEBULA_CORE_LOGIN_MAX_ATTEMPTS": "5",
            "NEBULA_CORE_LOGIN_WINDOW_SECONDS": "300",
            "NEBULA_CORE_LOGIN_LOCKOUT_SECONDS": "900",
            "NEBULA_CORS_ORIGINS": origins,
            "NEBULA_PANEL_GROUP": config.shared_group,
        }
        for key in SECRET_KEYS:
            core[key] = (
                secrets.token_urlsafe(48)
                if rotate_secrets
                else _production_secret(core.get(key, ""))
            )
    else:
        managed = {
            "NEBULA_CORE_HOST": "127.0.0.1",
            "NEBULA_CORE_PORT": str(config.core_port),
            "NEBULA_CORE_WORKERS": "1",
            "NEBULA_CORE_RELOAD": "true",
            "NEBULA_CORE_GRPC_HOST": "127.0.0.1",
            "NEBULA_CORE_GRPC_PORT": "50051",
            "NEBULA_COOKIE_SECURE": "false",
            "NEBULA_SESSION_TTL_SECONDS": "86400",
            "NEBULA_TOTP_VALID_WINDOW": "2",
            "NEBULA_CORE_LOGIN_MAX_ATTEMPTS": "20",
            "NEBULA_CORE_LOGIN_WINDOW_SECONDS": "300",
            "NEBULA_CORE_LOGIN_LOCKOUT_SECONDS": "60",
            "NEBULA_CORS_ORIGINS": (
                f"http://127.0.0.1:{config.panel_port},"
                f"http://localhost:{config.panel_port}"
            ),
            "NEBULA_PANEL_GROUP": config.shared_group or config.core_user,
        }
        dev_secrets = {
            "NEBULA_SESSION_SECRET": "nebula-dev-session-secret-local-only",
            "NEBULA_INSTALLER_TOKEN": "nebula-dev-installer-token-local-only",
            "NEBULA_PASSWORD_RESET_SECRET": "nebula-dev-reset-secret-local-only",
        }
        for key, value in dev_secrets.items():
            if rotate_secrets or not core.get(key):
                core[key] = value

    core.update(managed)
    _write(
        core_path,
        render_env(core, "Nebula Core environment"),
        config=config,
        runner=runner,
        owner=config.core_user,
    )
    if legacy_path.exists():
        archived = config.core_path / ".env.pre-nebula-installer"
        suffix = 1
        while archived.exists():
            archived = config.core_path / f".env.pre-nebula-installer.{suffix}"
            suffix += 1
        if config.mode == MODE_PROD:
            runner.sudo(["mv", str(legacy_path), str(archived)])
        else:
            legacy_path.rename(archived)

    panel_path = config.panel_path / ".env"
    panel = read_env_file(panel_path, runner if config.mode == MODE_PROD else None)
    panel.update(
        {
            "NEBULA_CORE_URL": config.panel_core_url,
            "NEBULA_INSTALLER_TOKEN": core["NEBULA_INSTALLER_TOKEN"],
            "HOST": config.panel_host,
            "PORT": str(config.panel_port),
            "NODE_ENV": "production" if config.mode == MODE_PROD else "development",
        }
    )
    _write(
        panel_path,
        render_env(panel, "Nebula Panel environment"),
        config=config,
        runner=runner,
        owner=config.panel_user,
    )
    return core


def configure_core_profile(config: DeploymentConfig, runner: Runner) -> None:
    source_path = config.core_path / "nebula_core/serviceconfig.yaml"
    path = config.core_path / "serviceconfig.yaml"
    try:
        content = source_path.read_text(encoding="utf-8")
    except OSError as exc:
        raise CommandError(f"Cannot read Core profile {source_path}: {exc}") from exc

    production = config.mode == MODE_PROD
    replacements: dict[str, str] = {
        "environment": '"production"' if production else '"development"',
        "in_process_enabled": "false" if production else "true",
        "process_runtime_enabled": "true" if production else "false",
        "cgroup_enabled": "true" if production else "false",
        "cgroup_required": "false",
        "allow_remote_grpc": "false",
    }
    for key, value in replacements.items():
        pattern = rf"(?m)^(\s{{2}}{re.escape(key)}:\s*).*$"
        content, count = re.subn(pattern, rf"\g<1>{value}", content, count=1)
        if count != 1:
            raise CommandError(f"Core profile is incompatible: missing plugins.{key}")

    if production:
        runtime_values = {
            "runtime_socket_dir": '"/run/nebula-core/plugins"',
            "runtime_log_dir": f'"{config.core_path}/storage/plugin-logs"',
        }
        for key, value in runtime_values.items():
            content = re.sub(
                rf"(?m)^(\s{{2}}{re.escape(key)}:\s*).*$",
                rf"\g<1>{value}",
                content,
                count=1,
            )

    if config.mode == MODE_PROD:
        runner.install_text(
            path,
            content,
            mode=0o640,
            owner=config.core_user,
            group=config.core_user,
        )
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    exclude_path = config.core_path / ".git/info/exclude"
    exclude = ""
    try:
        exclude = exclude_path.read_text(encoding="utf-8")
    except OSError:
        if config.mode == MODE_PROD:
            result = runner.sudo(["cat", str(exclude_path)], check=False)
            exclude = result.stdout if result.returncode == 0 else ""
    rule = "/serviceconfig.yaml"
    if rule not in {line.strip() for line in exclude.splitlines()}:
        exclude = (
            exclude.rstrip()
            + "\n# Nebula Installer generated runtime profile\n"
            + rule
            + "\n"
        )
        if config.mode == MODE_PROD:
            runner.install_text(
                exclude_path,
                exclude,
                mode=0o644,
                owner=config.core_user,
                group=config.core_user,
            )
        else:
            exclude_path.parent.mkdir(parents=True, exist_ok=True)
            exclude_path.write_text(exclude, encoding="utf-8")


def prepare_storage(config: DeploymentConfig, runner: Runner) -> None:
    directories = [
        (config.core_path / "storage/databases", 0o700),
        (config.core_path / "storage/logs", 0o750),
        (config.core_path / "storage/container_workspaces", 0o770),
        (config.core_path / "storage/plugin-logs", 0o750),
        (config.core_path / "logs", 0o750),
        (config.panel_path / "logs", 0o750),
    ]
    for path, mode in directories:
        if config.mode == MODE_PROD:
            owner = (
                config.panel_user
                if path == config.panel_path / "logs"
                else config.core_user
            )
            runner.ensure_directory(
                path,
                owner=owner,
                group=owner,
                mode=mode,
                privileged=True,
            )
        else:
            path.mkdir(parents=True, exist_ok=True)
            path.chmod(mode)
